# ===============================
# Example secrets configuration
# Copy this file to:
#   .streamlit/secrets.toml
# and replace the placeholders.
# ===============================

[api]
# List of API keys
keys = ["REPLACE_WITH_KEY_1", "REPLACE_WITH_KEY_2", "REPLACE_WITH_KEY_3"]

# List of models linked to the keys above
models = ["REPLACE_WITH_MODEL_1", "REPLACE_WITH_MODEL_2", "REPLACE_WITH_MODEL_3"]

# List of base urls of the chosen models
models = ["REPLACE_WITH_URL_1", "REPLACE_WITH_URL_2", "REPLACE_WITH_URL_3"]

[prompts]
# Prompts for different languages
prompt_en = "REPLACE_WITH_ENGLISH_PROMPT"
prompt_pt = "REPLACE_WITH_PORTUGUESE_PROMPT"